(*Generated by Sail from User.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import SailStdpp.ConcurrencyInterfaceTypesV2.
Require Import SailStdpp.ConcurrencyInterfaceV2.
Require Import SailStdpp.ConcurrencyInterfaceBuiltinsV2.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

From SailArm Require Export armv9_types.

Definition reg_index : Type := Z.

Definition datasize : Type := bitU.

Inductive extend_type := UXTB | UXTH | UXTW | UXTX | SXTB | SXTH | SXTW | SXTX.
Definition num_of_extend_type (arg_ : extend_type) : Z :=
   match arg_ with
   | UXTB => 0
   | UXTH => 1
   | UXTW => 2
   | UXTX => 3
   | SXTB => 4
   | SXTH => 5
   | SXTW => 6
   | SXTX => 7
   end.

Definition extend_type_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 7)*) : extend_type :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then UXTB
   else if Z.eqb (l__0) (1) then UXTH
   else if Z.eqb (l__0) (2) then UXTW
   else if Z.eqb (l__0) (3) then UXTX
   else if Z.eqb (l__0) (4) then SXTB
   else if Z.eqb (l__0) (5) then SXTH
   else if Z.eqb (l__0) (6) then SXTW
   else SXTX.

Lemma extend_type_num_of_roundtrip (x : extend_type) : extend_type_of_num (num_of_extend_type x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_extend_type_injective (x y : extend_type) : num_of_extend_type x = num_of_extend_type y -> x = y.
  intro.
  rewrite <- (extend_type_num_of_roundtrip x).
  rewrite <- (extend_type_num_of_roundtrip y).
  congruence.
Qed.
Definition extend_type_eq_dec (x y : extend_type) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_extend_type x) (num_of_extend_type y) with
  | left e => left (num_of_extend_type_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition extend_type_beq (x y : extend_type) : bool :=
  Z.eqb (num_of_extend_type x) (num_of_extend_type y).
Lemma extend_type_beq_iff x y : extend_type_beq x y = true <-> x = y.
  unfold extend_type_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_extend_type_injective | congruence].
Qed.
Lemma extend_type_beq_refl x : extend_type_beq x x = true.
apply extend_type_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_extend_type : EqDecision extend_type := extend_type_eq_dec.
#[export]
Instance Countable_extend_type : Countable extend_type.
refine {|
  encode x := encode (num_of_extend_type x);
  decode x := z ← decode x; mret (extend_type_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite extend_type_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_extend_type : Inhabited extend_type := { inhabitant := UXTB }.


Inductive shift_type := shift_LSL | shift_LSR | shift_ASR | shift_ROR.
Definition num_of_shift_type (arg_ : shift_type) : Z :=
   match arg_ with | shift_LSL => 0 | shift_LSR => 1 | shift_ASR => 2 | shift_ROR => 3 end.

Definition shift_type_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 3)*) : shift_type :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then shift_LSL
   else if Z.eqb (l__0) (1) then shift_LSR
   else if Z.eqb (l__0) (2) then shift_ASR
   else shift_ROR.

Lemma shift_type_num_of_roundtrip (x : shift_type) : shift_type_of_num (num_of_shift_type x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_shift_type_injective (x y : shift_type) : num_of_shift_type x = num_of_shift_type y -> x = y.
  intro.
  rewrite <- (shift_type_num_of_roundtrip x).
  rewrite <- (shift_type_num_of_roundtrip y).
  congruence.
Qed.
Definition shift_type_eq_dec (x y : shift_type) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_shift_type x) (num_of_shift_type y) with
  | left e => left (num_of_shift_type_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition shift_type_beq (x y : shift_type) : bool :=
  Z.eqb (num_of_shift_type x) (num_of_shift_type y).
Lemma shift_type_beq_iff x y : shift_type_beq x y = true <-> x = y.
  unfold shift_type_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_shift_type_injective | congruence].
Qed.
Lemma shift_type_beq_refl x : shift_type_beq x x = true.
apply shift_type_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_shift_type : EqDecision shift_type := shift_type_eq_dec.
#[export]
Instance Countable_shift_type : Countable shift_type.
refine {|
  encode x := encode (num_of_shift_type x);
  decode x := z ← decode x; mret (shift_type_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite shift_type_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_shift_type : Inhabited shift_type := { inhabitant := shift_LSL }.


Inductive operand :=
| OperandRegExt : (reg_index * extend_type * Z) -> operand
| OperandRegShift : (reg_index * shift_type * Z) -> operand
| OperandImm : bits 64 -> operand.
Arguments operand : clear implicits.

Definition sail_operand_encode (x : operand) := match x with
  | OperandRegExt x' => encode (0, encode x')
  | OperandRegShift x' => encode (1, encode x')
  | OperandImm x' => encode (2, encode x') end.
Definition sail_operand_decode x : option operand := match decode x with
  | Some (0, x') => OperandRegExt <$> decode x'
  | Some (1, x') => OperandRegShift <$> decode x'
  | Some (2, x') => OperandImm <$> decode x'
  | _ => None end.
Lemma sail_operand_decode_encode : forall (x : operand), sail_operand_decode (sail_operand_encode x)
   = Some x.
Proof.
  unfold sail_operand_decode, sail_operand_encode;
  intros [x|x|x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_operand : EqDecision operand := decode_encode_eq_dec sail_operand_encode
  sail_operand_decode sail_operand_decode_encode .

#[export]
Instance Countable_operand : Countable operand := {|
  encode := sail_operand_encode;
  decode := sail_operand_decode;
  decode_encode := sail_operand_decode_encode
|}.
#[export]
Instance dummy_operand : Inhabited (operand) := { inhabitant := OperandRegExt inhabitant }.

Inductive bitwise_op := Eor | Or | And.
Definition num_of_bitwise_op (arg_ : bitwise_op) : Z :=
   match arg_ with | Eor => 0 | Or => 1 | And => 2 end.

Definition bitwise_op_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 2)*) : bitwise_op :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then Eor
   else if Z.eqb (l__0) (1) then Or
   else And.

Lemma bitwise_op_num_of_roundtrip (x : bitwise_op) : bitwise_op_of_num (num_of_bitwise_op x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_bitwise_op_injective (x y : bitwise_op) : num_of_bitwise_op x = num_of_bitwise_op y -> x = y.
  intro.
  rewrite <- (bitwise_op_num_of_roundtrip x).
  rewrite <- (bitwise_op_num_of_roundtrip y).
  congruence.
Qed.
Definition bitwise_op_eq_dec (x y : bitwise_op) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_bitwise_op x) (num_of_bitwise_op y) with
  | left e => left (num_of_bitwise_op_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition bitwise_op_beq (x y : bitwise_op) : bool :=
  Z.eqb (num_of_bitwise_op x) (num_of_bitwise_op y).
Lemma bitwise_op_beq_iff x y : bitwise_op_beq x y = true <-> x = y.
  unfold bitwise_op_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_bitwise_op_injective | congruence].
Qed.
Lemma bitwise_op_beq_refl x : bitwise_op_beq x x = true.
apply bitwise_op_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_bitwise_op : EqDecision bitwise_op := bitwise_op_eq_dec.
#[export]
Instance Countable_bitwise_op : Countable bitwise_op.
refine {|
  encode x := encode (num_of_bitwise_op x);
  decode x := z ← decode x; mret (bitwise_op_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite bitwise_op_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_bitwise_op : Inhabited bitwise_op := { inhabitant := Eor }.


Inductive cond := EQ' | NE | CS | CC | MI | PL | VS | VC | HI | LS | GE | LT' | GT' | LE | AL | NV.
Definition num_of_cond (arg_ : cond) : Z :=
   match arg_ with
   | EQ' => 0
   | NE => 1
   | CS => 2
   | CC => 3
   | MI => 4
   | PL => 5
   | VS => 6
   | VC => 7
   | HI => 8
   | LS => 9
   | GE => 10
   | LT' => 11
   | GT' => 12
   | LE => 13
   | AL => 14
   | NV => 15
   end.

Definition cond_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 15)*) : cond :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then EQ'
   else if Z.eqb (l__0) (1) then NE
   else if Z.eqb (l__0) (2) then CS
   else if Z.eqb (l__0) (3) then CC
   else if Z.eqb (l__0) (4) then MI
   else if Z.eqb (l__0) (5) then PL
   else if Z.eqb (l__0) (6) then VS
   else if Z.eqb (l__0) (7) then VC
   else if Z.eqb (l__0) (8) then HI
   else if Z.eqb (l__0) (9) then LS
   else if Z.eqb (l__0) (10) then GE
   else if Z.eqb (l__0) (11) then LT'
   else if Z.eqb (l__0) (12) then GT'
   else if Z.eqb (l__0) (13) then LE
   else if Z.eqb (l__0) (14) then AL
   else NV.

Lemma cond_num_of_roundtrip (x : cond) : cond_of_num (num_of_cond x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_cond_injective (x y : cond) : num_of_cond x = num_of_cond y -> x = y.
  intro.
  rewrite <- (cond_num_of_roundtrip x).
  rewrite <- (cond_num_of_roundtrip y).
  congruence.
Qed.
Definition cond_eq_dec (x y : cond) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_cond x) (num_of_cond y) with
  | left e => left (num_of_cond_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition cond_beq (x y : cond) : bool :=
  Z.eqb (num_of_cond x) (num_of_cond y).
Lemma cond_beq_iff x y : cond_beq x y = true <-> x = y.
  unfold cond_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_cond_injective | congruence].
Qed.
Lemma cond_beq_refl x : cond_beq x x = true.
apply cond_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_cond : EqDecision cond := cond_eq_dec.
#[export]
Instance Countable_cond : Countable cond.
refine {|
  encode x := encode (num_of_cond x);
  decode x := z ← decode x; mret (cond_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite cond_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_cond : Inhabited cond := { inhabitant := EQ' }.


Inductive ast :=
| Load : (Z * reg_index * reg_index * operand * bool * bool * bool) -> ast
| Store : (Z * reg_index * reg_index * operand * bool * option reg_index) -> ast
| BitwiseLogic : (datasize * bitwise_op * reg_index * reg_index * operand) -> ast
| Movz : (datasize * reg_index * bits 16 * Z) -> ast
| AddSub : (datasize * bitU * bitU * reg_index * reg_index * operand) -> ast
| DataMemoryBarrierInstr : (MBReqDomain * MBReqTypes) -> ast
| DataSynchronizationBarrierInstr : (MBReqDomain * MBReqTypes) -> ast
| InstructionSynchronizationBarrierInstr : unit -> ast
| Nop : unit -> ast
| CompareAndBranch : (datasize * reg_index * bits 64 * bool) -> ast
| Branch : bits 64 -> ast
| ConditionalBranch : (bits 64 * cond) -> ast
| Adr : (reg_index * bits 64) -> ast
| BranchRegister : reg_index -> ast.
Arguments ast : clear implicits.

Definition sail_ast_encode (x : ast) := match x with
  | Load x' => encode (0, encode x')
  | Store x' => encode (1, encode x')
  | BitwiseLogic x' => encode (2, encode x')
  | Movz x' => encode (3, encode x')
  | AddSub x' => encode (4, encode x')
  | DataMemoryBarrierInstr x' => encode (5, encode x')
  | DataSynchronizationBarrierInstr x' => encode (6, encode x')
  | InstructionSynchronizationBarrierInstr x' => encode (7, encode x')
  | Nop x' => encode (8, encode x')
  | CompareAndBranch x' => encode (9, encode x')
  | Branch x' => encode (10, encode x')
  | ConditionalBranch x' => encode (11, encode x')
  | Adr x' => encode (12, encode x')
  | BranchRegister x' => encode (13, encode x') end.
Definition sail_ast_decode x : option ast := match decode x with
  | Some (0, x') => Load <$> decode x'
  | Some (1, x') => Store <$> decode x'
  | Some (2, x') => BitwiseLogic <$> decode x'
  | Some (3, x') => Movz <$> decode x'
  | Some (4, x') => AddSub <$> decode x'
  | Some (5, x') => DataMemoryBarrierInstr <$> decode x'
  | Some (6, x') => DataSynchronizationBarrierInstr <$> decode x'
  | Some (7, x') => InstructionSynchronizationBarrierInstr <$> decode x'
  | Some (8, x') => Nop <$> decode x'
  | Some (9, x') => CompareAndBranch <$> decode x'
  | Some (10, x') => Branch <$> decode x'
  | Some (11, x') => ConditionalBranch <$> decode x'
  | Some (12, x') => Adr <$> decode x'
  | Some (13, x') => BranchRegister <$> decode x'
  | _ => None end.
Lemma sail_ast_decode_encode : forall (x : ast), sail_ast_decode (sail_ast_encode x)  = Some x.
Proof.
  unfold sail_ast_decode, sail_ast_encode;
  intros [x|x|x|x|x|x|x|x|x|x|x|x|x|x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_ast : EqDecision ast := decode_encode_eq_dec sail_ast_encode sail_ast_decode
  sail_ast_decode_encode .

#[export]
Instance Countable_ast : Countable ast := {|
  encode := sail_ast_encode;
  decode := sail_ast_decode;
  decode_encode := sail_ast_decode_encode
|}.
#[export]
Instance dummy_ast : Inhabited (ast) := { inhabitant := Load inhabitant }.

Definition addr_size : Z := 64.
#[export] Hint Unfold addr_size : sail.

Definition addr_space : Type := unit.

Definition abort : Type := unit.

Definition mem_acc_is_explicit (acc : AccessDescriptor) : bool :=
   generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR).

Definition mem_acc_is_ifetch (acc : AccessDescriptor) : bool :=
   generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_IFETCH).

Definition mem_acc_is_ttw (acc : AccessDescriptor) : bool :=
   generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_TTW).

Definition mem_acc_is_relaxed (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     ((andb ((negb (acc.(AccessDescriptor_acqpc))))
         ((andb ((negb (acc.(AccessDescriptor_acqsc)))) ((negb (acc.(AccessDescriptor_relsc)))))))).

Definition mem_acc_is_rel_acq_rcpc (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     (acc.(AccessDescriptor_acqpc)).

Definition mem_acc_is_rel_acq_rcsc (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     ((orb (acc.(AccessDescriptor_acqsc)) (acc.(AccessDescriptor_relsc)))).

Definition mem_acc_is_standalone (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     ((andb ((negb (acc.(AccessDescriptor_exclusive)))) ((negb (acc.(AccessDescriptor_atomicop)))))).

Definition mem_acc_is_exclusive (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     (acc.(AccessDescriptor_exclusive)).

Definition mem_acc_is_atomic_rmw (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     (acc.(AccessDescriptor_atomicop)).



Variant register_bitvector_4 :=
  | NZCV
.

Definition num_of_register_bitvector_4 (r : register_bitvector_4) : Z :=
  match r with
  | NZCV => 0
  end.
Definition register_bitvector_4_of_num (i : Z) : register_bitvector_4 :=
  match i with
  | 0 => NZCV
  | _ => NZCV
  end.
Lemma register_bitvector_4_num_of_roundtrip (x : register_bitvector_4) : register_bitvector_4_of_num (num_of_register_bitvector_4 x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_register_bitvector_4_injective (x y : register_bitvector_4) : num_of_register_bitvector_4 x = num_of_register_bitvector_4 y -> x = y.
  intro.
  rewrite <- (register_bitvector_4_num_of_roundtrip x).
  rewrite <- (register_bitvector_4_num_of_roundtrip y).
  congruence.
Qed.
Definition register_bitvector_4_eq_dec (x y : register_bitvector_4) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_register_bitvector_4 x) (num_of_register_bitvector_4 y) with
  | left e => left (num_of_register_bitvector_4_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition register_bitvector_4_beq (x y : register_bitvector_4) : bool :=
  Z.eqb (num_of_register_bitvector_4 x) (num_of_register_bitvector_4 y).
Lemma register_bitvector_4_beq_iff x y : register_bitvector_4_beq x y = true <-> x = y.
  unfold register_bitvector_4_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_register_bitvector_4_injective | congruence].
Qed.
Lemma register_bitvector_4_beq_refl x : register_bitvector_4_beq x x = true.
apply register_bitvector_4_beq_iff; reflexivity.
Qed.
Hint Rewrite register_bitvector_4_beq_iff : register_beq_iffs.
Hint Rewrite register_bitvector_4_beq_refl : register_beq_refls.
Definition register_bitvector_4_list : list (string * register_bitvector_4) := [
  ("NZCV", NZCV)
].

Instance Decidable_eq_register_bitvector_4 : EqDecision register_bitvector_4 := register_bitvector_4_eq_dec.
Instance Countable_register_bitvector_4 : Countable register_bitvector_4. refine {|
  encode x := encode (num_of_register_bitvector_4 x);
  decode x := register_bitvector_4_of_num <$> decode x
|}.
  intro s; rewrite decode_encode; simpl.
  rewrite register_bitvector_4_num_of_roundtrip.
  reflexivity.
Defined.

Variant register_bitvector_64 :=
  | _PC
  | R30
  | R29
  | R28
  | R27
  | R26
  | R25
  | R24
  | R23
  | R22
  | R21
  | R20
  | R19
  | R18
  | R17
  | R16
  | R15
  | R14
  | R13
  | R12
  | R11
  | R10
  | R9
  | R8
  | R7
  | R6
  | R5
  | R4
  | R3
  | R2
  | R1
  | R0
  | SP_EL0
.

Definition num_of_register_bitvector_64 (r : register_bitvector_64) : Z :=
  match r with
  | _PC => 0
  | R30 => 1
  | R29 => 2
  | R28 => 3
  | R27 => 4
  | R26 => 5
  | R25 => 6
  | R24 => 7
  | R23 => 8
  | R22 => 9
  | R21 => 10
  | R20 => 11
  | R19 => 12
  | R18 => 13
  | R17 => 14
  | R16 => 15
  | R15 => 16
  | R14 => 17
  | R13 => 18
  | R12 => 19
  | R11 => 20
  | R10 => 21
  | R9 => 22
  | R8 => 23
  | R7 => 24
  | R6 => 25
  | R5 => 26
  | R4 => 27
  | R3 => 28
  | R2 => 29
  | R1 => 30
  | R0 => 31
  | SP_EL0 => 32
  end.
Definition register_bitvector_64_of_num (i : Z) : register_bitvector_64 :=
  match i with
  | 0 => _PC
  | 1 => R30
  | 2 => R29
  | 3 => R28
  | 4 => R27
  | 5 => R26
  | 6 => R25
  | 7 => R24
  | 8 => R23
  | 9 => R22
  | 10 => R21
  | 11 => R20
  | 12 => R19
  | 13 => R18
  | 14 => R17
  | 15 => R16
  | 16 => R15
  | 17 => R14
  | 18 => R13
  | 19 => R12
  | 20 => R11
  | 21 => R10
  | 22 => R9
  | 23 => R8
  | 24 => R7
  | 25 => R6
  | 26 => R5
  | 27 => R4
  | 28 => R3
  | 29 => R2
  | 30 => R1
  | 31 => R0
  | 32 => SP_EL0
  | _ => _PC
  end.
Lemma register_bitvector_64_num_of_roundtrip (x : register_bitvector_64) : register_bitvector_64_of_num (num_of_register_bitvector_64 x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_register_bitvector_64_injective (x y : register_bitvector_64) : num_of_register_bitvector_64 x = num_of_register_bitvector_64 y -> x = y.
  intro.
  rewrite <- (register_bitvector_64_num_of_roundtrip x).
  rewrite <- (register_bitvector_64_num_of_roundtrip y).
  congruence.
Qed.
Definition register_bitvector_64_eq_dec (x y : register_bitvector_64) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_register_bitvector_64 x) (num_of_register_bitvector_64 y) with
  | left e => left (num_of_register_bitvector_64_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition register_bitvector_64_beq (x y : register_bitvector_64) : bool :=
  Z.eqb (num_of_register_bitvector_64 x) (num_of_register_bitvector_64 y).
Lemma register_bitvector_64_beq_iff x y : register_bitvector_64_beq x y = true <-> x = y.
  unfold register_bitvector_64_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_register_bitvector_64_injective | congruence].
Qed.
Lemma register_bitvector_64_beq_refl x : register_bitvector_64_beq x x = true.
apply register_bitvector_64_beq_iff; reflexivity.
Qed.
Hint Rewrite register_bitvector_64_beq_iff : register_beq_iffs.
Hint Rewrite register_bitvector_64_beq_refl : register_beq_refls.
Definition register_bitvector_64_list : list (string * register_bitvector_64) := [
  ("_PC", _PC);
  ("R30", R30);
  ("R29", R29);
  ("R28", R28);
  ("R27", R27);
  ("R26", R26);
  ("R25", R25);
  ("R24", R24);
  ("R23", R23);
  ("R22", R22);
  ("R21", R21);
  ("R20", R20);
  ("R19", R19);
  ("R18", R18);
  ("R17", R17);
  ("R16", R16);
  ("R15", R15);
  ("R14", R14);
  ("R13", R13);
  ("R12", R12);
  ("R11", R11);
  ("R10", R10);
  ("R9", R9);
  ("R8", R8);
  ("R7", R7);
  ("R6", R6);
  ("R5", R5);
  ("R4", R4);
  ("R3", R3);
  ("R2", R2);
  ("R1", R1);
  ("R0", R0);
  ("SP_EL0", SP_EL0)
].

Instance Decidable_eq_register_bitvector_64 : EqDecision register_bitvector_64 := register_bitvector_64_eq_dec.
Instance Countable_register_bitvector_64 : Countable register_bitvector_64. refine {|
  encode x := encode (num_of_register_bitvector_64 x);
  decode x := register_bitvector_64_of_num <$> decode x
|}.
  intro s; rewrite decode_encode; simpl.
  rewrite register_bitvector_64_num_of_roundtrip.
  reflexivity.
Defined.


Variant register : Type :=
  | R_bitvector_4 :> register_bitvector_4 -> register
  | R_bitvector_64 :> register_bitvector_64 -> register
.

Definition type_of_register (r : register) : Type :=
  match r with
  | R_bitvector_4 _ => ((mword 4))
  | R_bitvector_64 _ => ((mword 64))
  end.

  Definition register_encode (r : register) : positive :=
    match r with
    | R_bitvector_4 r => encode (0, encode r)
    | R_bitvector_64 r => encode (1, encode r)
    end.
  Definition register_decode (x : positive) : option register :=
    match decode x with
    | Some (0, y) => r ← decode y; mret (R_bitvector_4 r)
    | Some (1, y) => r ← decode y; mret (R_bitvector_64 r)
    | _ => None
    end.
  Lemma register_decode_encode r : register_decode (register_encode r) = Some r.
  Proof.
    destruct r;
    unfold register_decode, register_encode;
    rewrite !decode_encode;
    reflexivity.
  Qed.
  Lemma register_encode_inj r r' : register_encode r = register_encode r' -> r = r'.
  Proof.
    intro H.
    enough (Some r = Some r') by congruence.
    rewrite <- (register_decode_encode r).
    rewrite <- (register_decode_encode r').
    congruence.
  Qed.
  #[export] Instance Decidable_eq_register : EqDecision register.
  refine (fun r r' => match Pos.eq_dec (register_encode r) (register_encode r') with
  | left e => left (register_encode_inj _ _ e)
  | right ne => right _
  end).
  congruence.
  Defined.
  #[export] Instance Countable_register : Countable register := {|
    encode := register_encode;
    decode := register_decode;
    decode_encode := register_decode_encode;
  |}.

Definition register_transport {P : Type -> Type} {r r' : register} : r = r' -> P (type_of_register r) -> P (type_of_register r').
refine (
  match r, r' with
  | R_bitvector_4 r, R_bitvector_4 r' => fun _ x => x
  | R_bitvector_64 r, R_bitvector_64 r' => fun _ x => x
  | _, _ => fun e _ => _
  end
).
  all:
  enough (H : type_of_register r0 = type_of_register r1);
  [ simpl in H; congruence
  | rewrite e; reflexivity].
Defined.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) :
  register_transport e p = p.
Proof.
  destruct r; reflexivity.
Qed.

Definition register_beq (r r' : register) : bool :=
  match r, r' with
  | R_bitvector_4 r, R_bitvector_4 r' => register_bitvector_4_beq r r'
  | R_bitvector_64 r, R_bitvector_64 r' => register_bitvector_64_beq r r'
  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with
  | R_bitvector_4 r, R_bitvector_4 r' => fun p => if register_bitvector_4_beq r r' then Some p else None
  | R_bitvector_64 r, R_bitvector_64 r' => fun p => if register_bitvector_64_beq r r' then Some p else None
  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [
  List.map (fun '(s, r) => (s, R_bitvector_4 r)) register_bitvector_4_list;
  List.map (fun '(s, r) => (s, R_bitvector_64 r)) register_bitvector_64_list
].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with
  | R_bitvector_4 _ => _
  | R_bitvector_64 _ => _
end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with
  | R_bitvector_4 _ => _
  | R_bitvector_64 _ => _
end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with
  | R_bitvector_4 _ => encode
  | R_bitvector_64 _ => encode
  end;
  decode := match r with
  | R_bitvector_4 _ => decode
  | R_bitvector_64 _ => decode
  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.

Definition register_ref := @SailStdpp.Values.register_ref register type_of_register.

Definition NZCV_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "NZCV" NZCV (fun x => x) (fun x => x).
Instance dummy_register_bitvector_4 : Inhabited (register_ref _) := populate NZCV_ref.

Definition _PC_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "_PC" _PC (fun x => x) (fun x => x).
Definition R30_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R30" R30 (fun x => x) (fun x => x).
Definition R29_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R29" R29 (fun x => x) (fun x => x).
Definition R28_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R28" R28 (fun x => x) (fun x => x).
Definition R27_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R27" R27 (fun x => x) (fun x => x).
Definition R26_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R26" R26 (fun x => x) (fun x => x).
Definition R25_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R25" R25 (fun x => x) (fun x => x).
Definition R24_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R24" R24 (fun x => x) (fun x => x).
Definition R23_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R23" R23 (fun x => x) (fun x => x).
Definition R22_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R22" R22 (fun x => x) (fun x => x).
Definition R21_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R21" R21 (fun x => x) (fun x => x).
Definition R20_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R20" R20 (fun x => x) (fun x => x).
Definition R19_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R19" R19 (fun x => x) (fun x => x).
Definition R18_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R18" R18 (fun x => x) (fun x => x).
Definition R17_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R17" R17 (fun x => x) (fun x => x).
Definition R16_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R16" R16 (fun x => x) (fun x => x).
Definition R15_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R15" R15 (fun x => x) (fun x => x).
Definition R14_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R14" R14 (fun x => x) (fun x => x).
Definition R13_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R13" R13 (fun x => x) (fun x => x).
Definition R12_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R12" R12 (fun x => x) (fun x => x).
Definition R11_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R11" R11 (fun x => x) (fun x => x).
Definition R10_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R10" R10 (fun x => x) (fun x => x).
Definition R9_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R9" R9 (fun x => x) (fun x => x).
Definition R8_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R8" R8 (fun x => x) (fun x => x).
Definition R7_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R7" R7 (fun x => x) (fun x => x).
Definition R6_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R6" R6 (fun x => x) (fun x => x).
Definition R5_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R5" R5 (fun x => x) (fun x => x).
Definition R4_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R4" R4 (fun x => x) (fun x => x).
Definition R3_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R3" R3 (fun x => x) (fun x => x).
Definition R2_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R2" R2 (fun x => x) (fun x => x).
Definition R1_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R1" R1 (fun x => x) (fun x => x).
Definition R0_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "R0" R0 (fun x => x) (fun x => x).
Definition SP_EL0_ref : register_ref _ :=
  Build_register_ref register type_of_register _ "SP_EL0" SP_EL0 (fun x => x) (fun x => x).
Instance dummy_register_bitvector_64 : Inhabited (register_ref _) := populate _PC_ref.


(* Definitions to support the lifting to the sequential monad *)
Record regstate := {
  bitvector_4_s : register_bitvector_4 -> mword 4;
  bitvector_64_s : register_bitvector_64 -> mword 64;
}.
#[export] Instance eta_regstate : Settable _ := settable! Build_regstate <bitvector_4_s; bitvector_64_s>.

Definition init_regstate : regstate := Build_regstate
  inhabitant
  inhabitant
.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with
  | R_bitvector_4 r => rs.(bitvector_4_s) r
  | R_bitvector_64 r => rs.(bitvector_64_s) r
  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with
  | R_bitvector_4 r => fun v rs => rs <|bitvector_4_s := fun r' => if register_bitvector_4_beq r' r then v else rs.(bitvector_4_s) r'|>
  | R_bitvector_64 r => fun v rs => rs <|bitvector_64_s := fun r' => if register_bitvector_64_beq r' r then v else rs.(bitvector_64_s) r'|>
  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : SailStdpp.Values.register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @SailStdpp.Prompt_monad.read_reg register type_of_register E.
Definition write_reg {E} := @SailStdpp.Prompt_monad.write_reg register type_of_register E.

Module Arch <: SailStdpp.ConcurrencyInterfaceV2.Arch.
  Definition reg : Type := register.
  #[global] Typeclasses Transparent reg.
  Definition reg_eq := @Decidable_eq_register.
  Definition reg_countable := @Countable_register.
  Definition reg_pretty := @Pretty_register.
  Definition reg_type := type_of_register.
  Definition reg_type_eq := @Decidable_eq_register_values.
  Definition reg_type_countable := @Countable_register_values.
  Definition reg_type_inhabited := @Inhabited_register_values.
  Definition regval_transport := @register_transport (fun x => x).
  Definition regval_transport_sound := @register_transport_sound (fun x => x).
  Definition addr_size : N := Z.to_N (addr_size).
  Definition addr_space : Type := addr_space.
  Definition addr_space_eq : EqDecision addr_space := _.
  Definition addr_space_countable : Countable addr_space := _.
  Definition mem_acc : Type := AccessDescriptor.
  Definition mem_acc_eq : EqDecision mem_acc := _.
  Definition mem_acc_countable : Countable mem_acc := _.
  Definition CHERI : bool := (false).
  Definition cap_size_log : N := 0.
  Definition mem_acc_is_explicit := mem_acc_is_explicit.
  Definition mem_acc_is_ifetch := mem_acc_is_ifetch.
  Definition mem_acc_is_ttw := mem_acc_is_ttw.
  Definition mem_acc_is_relaxed := mem_acc_is_relaxed.
  Definition mem_acc_is_rel_acq_rcpc := mem_acc_is_rel_acq_rcpc.
  Definition mem_acc_is_rel_acq_rcsc := mem_acc_is_rel_acq_rcsc.
  Definition mem_acc_is_standalone := mem_acc_is_standalone.
  Definition mem_acc_is_exclusive := mem_acc_is_exclusive.
  Definition mem_acc_is_atomic_rmw := mem_acc_is_atomic_rmw.
  Definition trans_start : Type := unit.
  Definition trans_start_eq : EqDecision trans_start := _.
  Definition trans_start_countable : Countable trans_start := _.
  Definition trans_end : Type := unit.
  Definition trans_end_eq : EqDecision trans_end := _.
  Definition trans_end_countable : Countable trans_end := _.
  Definition abort : Type := abort.
  Definition abort_eq : EqDecision abort := _.
  Definition abort_countable : Countable abort := _.
  Definition barrier : Type := Barrier.
  Definition barrier_eq : EqDecision barrier := _.
  Definition barrier_countable : Countable barrier := _.
  Definition cache_op : Type := unit.
  Definition cache_op_eq : EqDecision cache_op := _.
  Definition cache_op_countable : Countable cache_op := _.
  Definition tlbi : Type := unit.
  Definition tlbi_eq : EqDecision tlbi := _.
  Definition tlbi_countable : Countable tlbi := _.
  Definition exn : Type := unit.
  Definition exn_eq : EqDecision exn := _.
  Definition exn_countable : Countable exn := _.
  Definition sys_reg_id : Type := unit.
  Definition sys_reg_id_eq : EqDecision sys_reg_id := _.
  Definition sys_reg_id_countable : Countable sys_reg_id := _.
End Arch.

Module Interface := SailStdpp.ConcurrencyInterfaceV2.Interface Arch.
Module Defs := SailStdpp.ConcurrencyInterfaceBuiltinsV2.Defs Arch Interface.

Definition M := Defs.monad unit.
Definition MR r := Defs.monad (r + unit)%type.
Definition returnM {A:Type} : A -> M A := Defs.returnm (E := unit).
Definition returnR {A:Type} (R:Type) : A -> MR R A := Defs.returnm (E := R + unit)%type.