(*Generated by Sail from User.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import SailStdpp.ConcurrencyInterfaceTypesV2.
Require Import SailStdpp.ConcurrencyInterfaceV2.
Require Import SailStdpp.ConcurrencyInterfaceBuiltinsV2.
From SailArm Require Export armv9_types.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition reg_index : Type := Z.

Definition datasize : Type := bitU.

Inductive extend_type := UXTB | UXTH | UXTW | UXTX | SXTB | SXTH | SXTW | SXTX.
Definition num_of_extend_type (arg_ : extend_type) : Z :=
   match arg_ with
   | UXTB => 0
   | UXTH => 1
   | UXTW => 2
   | UXTX => 3
   | SXTB => 4
   | SXTH => 5
   | SXTW => 6
   | SXTX => 7
   end.

Definition extend_type_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 7)*) : extend_type :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then UXTB
   else if Z.eqb (l__0) (1) then UXTH
   else if Z.eqb (l__0) (2) then UXTW
   else if Z.eqb (l__0) (3) then UXTX
   else if Z.eqb (l__0) (4) then SXTB
   else if Z.eqb (l__0) (5) then SXTH
   else if Z.eqb (l__0) (6) then SXTW
   else SXTX.

Lemma extend_type_num_of_roundtrip (x : extend_type) : extend_type_of_num (num_of_extend_type x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_extend_type_injective (x y : extend_type) : num_of_extend_type x = num_of_extend_type y -> x = y.
  intro.
  rewrite <- (extend_type_num_of_roundtrip x).
  rewrite <- (extend_type_num_of_roundtrip y).
  congruence.
Qed.
Definition extend_type_eq_dec (x y : extend_type) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_extend_type x) (num_of_extend_type y) with
  | left e => left (num_of_extend_type_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition extend_type_beq (x y : extend_type) : bool :=
  Z.eqb (num_of_extend_type x) (num_of_extend_type y).
Lemma extend_type_beq_iff x y : extend_type_beq x y = true <-> x = y.
  unfold extend_type_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_extend_type_injective | congruence].
Qed.
Lemma extend_type_beq_refl x : extend_type_beq x x = true.
apply extend_type_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_extend_type : EqDecision extend_type := extend_type_eq_dec.
#[export]
Instance Countable_extend_type : Countable extend_type.
refine {|
  encode x := encode (num_of_extend_type x);
  decode x := z ← decode x; mret (extend_type_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite extend_type_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_extend_type : Inhabited extend_type := { inhabitant := UXTB }.


Inductive shift_type := shift_LSL | shift_LSR | shift_ASR | shift_ROR.
Definition num_of_shift_type (arg_ : shift_type) : Z :=
   match arg_ with | shift_LSL => 0 | shift_LSR => 1 | shift_ASR => 2 | shift_ROR => 3 end.

Definition shift_type_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 3)*) : shift_type :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then shift_LSL
   else if Z.eqb (l__0) (1) then shift_LSR
   else if Z.eqb (l__0) (2) then shift_ASR
   else shift_ROR.

Lemma shift_type_num_of_roundtrip (x : shift_type) : shift_type_of_num (num_of_shift_type x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_shift_type_injective (x y : shift_type) : num_of_shift_type x = num_of_shift_type y -> x = y.
  intro.
  rewrite <- (shift_type_num_of_roundtrip x).
  rewrite <- (shift_type_num_of_roundtrip y).
  congruence.
Qed.
Definition shift_type_eq_dec (x y : shift_type) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_shift_type x) (num_of_shift_type y) with
  | left e => left (num_of_shift_type_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition shift_type_beq (x y : shift_type) : bool :=
  Z.eqb (num_of_shift_type x) (num_of_shift_type y).
Lemma shift_type_beq_iff x y : shift_type_beq x y = true <-> x = y.
  unfold shift_type_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_shift_type_injective | congruence].
Qed.
Lemma shift_type_beq_refl x : shift_type_beq x x = true.
apply shift_type_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_shift_type : EqDecision shift_type := shift_type_eq_dec.
#[export]
Instance Countable_shift_type : Countable shift_type.
refine {|
  encode x := encode (num_of_shift_type x);
  decode x := z ← decode x; mret (shift_type_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite shift_type_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_shift_type : Inhabited shift_type := { inhabitant := shift_LSL }.


Inductive operand :=
| OperandRegExt : (reg_index * extend_type * Z) -> operand
| OperandRegShift : (reg_index * shift_type * Z) -> operand
| OperandImm : bits 64 -> operand.
Arguments operand : clear implicits.

Definition sail_operand_encode (x : operand) := match x with
  | OperandRegExt x' => encode (0, encode x')
  | OperandRegShift x' => encode (1, encode x')
  | OperandImm x' => encode (2, encode x') end.
Definition sail_operand_decode x : option operand := match decode x with
  | Some (0, x') => OperandRegExt <$> decode x'
  | Some (1, x') => OperandRegShift <$> decode x'
  | Some (2, x') => OperandImm <$> decode x'
  | _ => None end.
Lemma sail_operand_decode_encode : forall (x : operand), sail_operand_decode (sail_operand_encode x)
   = Some x.
Proof.
  unfold sail_operand_decode, sail_operand_encode;
  intros [x|x|x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_operand : EqDecision operand := decode_encode_eq_dec sail_operand_encode
  sail_operand_decode sail_operand_decode_encode .

#[export]
Instance Countable_operand : Countable operand := {|
  encode := sail_operand_encode;
  decode := sail_operand_decode;
  decode_encode := sail_operand_decode_encode
|}.
#[export]
Instance dummy_operand : Inhabited (operand) := { inhabitant := OperandRegExt inhabitant }.

Inductive bitwise_op := Eor | Or | And.
Definition num_of_bitwise_op (arg_ : bitwise_op) : Z :=
   match arg_ with | Eor => 0 | Or => 1 | And => 2 end.

Definition bitwise_op_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 2)*) : bitwise_op :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then Eor
   else if Z.eqb (l__0) (1) then Or
   else And.

Lemma bitwise_op_num_of_roundtrip (x : bitwise_op) : bitwise_op_of_num (num_of_bitwise_op x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_bitwise_op_injective (x y : bitwise_op) : num_of_bitwise_op x = num_of_bitwise_op y -> x = y.
  intro.
  rewrite <- (bitwise_op_num_of_roundtrip x).
  rewrite <- (bitwise_op_num_of_roundtrip y).
  congruence.
Qed.
Definition bitwise_op_eq_dec (x y : bitwise_op) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_bitwise_op x) (num_of_bitwise_op y) with
  | left e => left (num_of_bitwise_op_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition bitwise_op_beq (x y : bitwise_op) : bool :=
  Z.eqb (num_of_bitwise_op x) (num_of_bitwise_op y).
Lemma bitwise_op_beq_iff x y : bitwise_op_beq x y = true <-> x = y.
  unfold bitwise_op_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_bitwise_op_injective | congruence].
Qed.
Lemma bitwise_op_beq_refl x : bitwise_op_beq x x = true.
apply bitwise_op_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_bitwise_op : EqDecision bitwise_op := bitwise_op_eq_dec.
#[export]
Instance Countable_bitwise_op : Countable bitwise_op.
refine {|
  encode x := encode (num_of_bitwise_op x);
  decode x := z ← decode x; mret (bitwise_op_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite bitwise_op_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_bitwise_op : Inhabited bitwise_op := { inhabitant := Eor }.


Inductive cond := EQ' | NE | CS | CC | MI | PL | VS | VC | HI | LS | GE | LT' | GT' | LE | AL | NV.
Definition num_of_cond (arg_ : cond) : Z :=
   match arg_ with
   | EQ' => 0
   | NE => 1
   | CS => 2
   | CC => 3
   | MI => 4
   | PL => 5
   | VS => 6
   | VC => 7
   | HI => 8
   | LS => 9
   | GE => 10
   | LT' => 11
   | GT' => 12
   | LE => 13
   | AL => 14
   | NV => 15
   end.

Definition cond_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 15)*) : cond :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then EQ'
   else if Z.eqb (l__0) (1) then NE
   else if Z.eqb (l__0) (2) then CS
   else if Z.eqb (l__0) (3) then CC
   else if Z.eqb (l__0) (4) then MI
   else if Z.eqb (l__0) (5) then PL
   else if Z.eqb (l__0) (6) then VS
   else if Z.eqb (l__0) (7) then VC
   else if Z.eqb (l__0) (8) then HI
   else if Z.eqb (l__0) (9) then LS
   else if Z.eqb (l__0) (10) then GE
   else if Z.eqb (l__0) (11) then LT'
   else if Z.eqb (l__0) (12) then GT'
   else if Z.eqb (l__0) (13) then LE
   else if Z.eqb (l__0) (14) then AL
   else NV.

Lemma cond_num_of_roundtrip (x : cond) : cond_of_num (num_of_cond x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_cond_injective (x y : cond) : num_of_cond x = num_of_cond y -> x = y.
  intro.
  rewrite <- (cond_num_of_roundtrip x).
  rewrite <- (cond_num_of_roundtrip y).
  congruence.
Qed.
Definition cond_eq_dec (x y : cond) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_cond x) (num_of_cond y) with
  | left e => left (num_of_cond_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition cond_beq (x y : cond) : bool :=
  Z.eqb (num_of_cond x) (num_of_cond y).
Lemma cond_beq_iff x y : cond_beq x y = true <-> x = y.
  unfold cond_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_cond_injective | congruence].
Qed.
Lemma cond_beq_refl x : cond_beq x x = true.
apply cond_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_cond : EqDecision cond := cond_eq_dec.
#[export]
Instance Countable_cond : Countable cond.
refine {|
  encode x := encode (num_of_cond x);
  decode x := z ← decode x; mret (cond_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite cond_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_cond : Inhabited cond := { inhabitant := EQ' }.


Inductive ast :=
| Load : (Z * reg_index * reg_index * operand * bool * bool * bool) -> ast
| Store : (Z * reg_index * reg_index * operand * bool * option reg_index) -> ast
| BitwiseLogic : (datasize * bitwise_op * reg_index * reg_index * operand) -> ast
| Movz : (datasize * reg_index * bits 16 * Z) -> ast
| AddSub : (datasize * bitU * bitU * reg_index * reg_index * operand) -> ast
| DataMemoryBarrierInstr : (MBReqDomain * MBReqTypes) -> ast
| DataSynchronizationBarrierInstr : (MBReqDomain * MBReqTypes) -> ast
| InstructionSynchronizationBarrierInstr : unit -> ast
| Nop : unit -> ast
| CompareAndBranch : (datasize * reg_index * bits 64 * bool) -> ast
| Branch : bits 64 -> ast
| ConditionalBranch : (bits 64 * cond) -> ast
| Adr : (reg_index * bits 64) -> ast
| BranchRegister : reg_index -> ast.
Arguments ast : clear implicits.

Definition sail_ast_encode (x : ast) := match x with
  | Load x' => encode (0, encode x')
  | Store x' => encode (1, encode x')
  | BitwiseLogic x' => encode (2, encode x')
  | Movz x' => encode (3, encode x')
  | AddSub x' => encode (4, encode x')
  | DataMemoryBarrierInstr x' => encode (5, encode x')
  | DataSynchronizationBarrierInstr x' => encode (6, encode x')
  | InstructionSynchronizationBarrierInstr x' => encode (7, encode x')
  | Nop x' => encode (8, encode x')
  | CompareAndBranch x' => encode (9, encode x')
  | Branch x' => encode (10, encode x')
  | ConditionalBranch x' => encode (11, encode x')
  | Adr x' => encode (12, encode x')
  | BranchRegister x' => encode (13, encode x') end.
Definition sail_ast_decode x : option ast := match decode x with
  | Some (0, x') => Load <$> decode x'
  | Some (1, x') => Store <$> decode x'
  | Some (2, x') => BitwiseLogic <$> decode x'
  | Some (3, x') => Movz <$> decode x'
  | Some (4, x') => AddSub <$> decode x'
  | Some (5, x') => DataMemoryBarrierInstr <$> decode x'
  | Some (6, x') => DataSynchronizationBarrierInstr <$> decode x'
  | Some (7, x') => InstructionSynchronizationBarrierInstr <$> decode x'
  | Some (8, x') => Nop <$> decode x'
  | Some (9, x') => CompareAndBranch <$> decode x'
  | Some (10, x') => Branch <$> decode x'
  | Some (11, x') => ConditionalBranch <$> decode x'
  | Some (12, x') => Adr <$> decode x'
  | Some (13, x') => BranchRegister <$> decode x'
  | _ => None end.
Lemma sail_ast_decode_encode : forall (x : ast), sail_ast_decode (sail_ast_encode x)  = Some x.
Proof.
  unfold sail_ast_decode, sail_ast_encode;
  intros [x|x|x|x|x|x|x|x|x|x|x|x|x|x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_ast : EqDecision ast := decode_encode_eq_dec sail_ast_encode sail_ast_decode
  sail_ast_decode_encode .

#[export]
Instance Countable_ast : Countable ast := {|
  encode := sail_ast_encode;
  decode := sail_ast_decode;
  decode_encode := sail_ast_decode_encode
|}.
#[export]
Instance dummy_ast : Inhabited (ast) := { inhabitant := Load inhabitant }.

Definition addr_size : Z := 64.
#[export] Hint Unfold addr_size : sail.

Definition addr_space : Type := unit.

Definition abort : Type := unit.

Definition mem_acc_is_explicit (acc : AccessDescriptor) : bool :=
   generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR).

Definition mem_acc_is_ifetch (acc : AccessDescriptor) : bool :=
   generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_IFETCH).

Definition mem_acc_is_ttw (acc : AccessDescriptor) : bool :=
   generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_TTW).

Definition mem_acc_is_relaxed (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     ((andb ((negb (acc.(AccessDescriptor_acqpc))))
         ((andb ((negb (acc.(AccessDescriptor_acqsc)))) ((negb (acc.(AccessDescriptor_relsc)))))))).

Definition mem_acc_is_rel_acq_rcpc (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     (acc.(AccessDescriptor_acqpc)).

Definition mem_acc_is_rel_acq_rcsc (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     ((orb (acc.(AccessDescriptor_acqsc)) (acc.(AccessDescriptor_relsc)))).

Definition mem_acc_is_standalone (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     ((andb ((negb (acc.(AccessDescriptor_exclusive)))) ((negb (acc.(AccessDescriptor_atomicop)))))).

Definition mem_acc_is_exclusive (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     (acc.(AccessDescriptor_exclusive)).

Definition mem_acc_is_atomic_rmw (acc : AccessDescriptor) : bool :=
   andb ((generic_eq (acc.(AccessDescriptor_acctype)) (AccessType_GPR)))
     (acc.(AccessDescriptor_atomicop)).



Definition register_accessors : SailStdpp.Values.register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @SailStdpp.Prompt_monad.read_reg register type_of_register E.
Definition write_reg {E} := @SailStdpp.Prompt_monad.write_reg register type_of_register E.

Module Arch <: SailStdpp.ConcurrencyInterfaceV2.Arch.
  Definition reg : Type := register.
  #[global] Typeclasses Transparent reg.
  Definition reg_eq := @Decidable_eq_register.
  Definition reg_countable := @Countable_register.
  Definition reg_pretty := @Pretty_register.
  Definition reg_type := type_of_register.
  Definition reg_type_eq := @Decidable_eq_register_values.
  Definition reg_type_countable := @Countable_register_values.
  Definition reg_type_inhabited := @Inhabited_register_values.
  Definition regval_transport := @register_transport (fun x => x).
  Definition regval_transport_sound := @register_transport_sound (fun x => x).
  Definition addr_size : N := Z.to_N (addr_size).
  Definition addr_space : Type := addr_space.
  Definition addr_space_eq : EqDecision addr_space := _.
  Definition addr_space_countable : Countable addr_space := _.
  Definition mem_acc : Type := AccessDescriptor.
  Definition mem_acc_eq : EqDecision mem_acc := _.
  Definition mem_acc_countable : Countable mem_acc := _.
  Definition CHERI : bool := (false).
  Definition cap_size_log : N := 0.
  Definition mem_acc_is_explicit := mem_acc_is_explicit.
  Definition mem_acc_is_ifetch := mem_acc_is_ifetch.
  Definition mem_acc_is_ttw := mem_acc_is_ttw.
  Definition mem_acc_is_relaxed := mem_acc_is_relaxed.
  Definition mem_acc_is_rel_acq_rcpc := mem_acc_is_rel_acq_rcpc.
  Definition mem_acc_is_rel_acq_rcsc := mem_acc_is_rel_acq_rcsc.
  Definition mem_acc_is_standalone := mem_acc_is_standalone.
  Definition mem_acc_is_exclusive := mem_acc_is_exclusive.
  Definition mem_acc_is_atomic_rmw := mem_acc_is_atomic_rmw.
  Definition trans_start : Type := unit.
  Definition trans_start_eq : EqDecision trans_start := _.
  Definition trans_start_countable : Countable trans_start := _.
  Definition trans_end : Type := unit.
  Definition trans_end_eq : EqDecision trans_end := _.
  Definition trans_end_countable : Countable trans_end := _.
  Definition abort : Type := abort.
  Definition abort_eq : EqDecision abort := _.
  Definition abort_countable : Countable abort := _.
  Definition barrier : Type := Barrier.
  Definition barrier_eq : EqDecision barrier := _.
  Definition barrier_countable : Countable barrier := _.
  Definition cache_op : Type := unit.
  Definition cache_op_eq : EqDecision cache_op := _.
  Definition cache_op_countable : Countable cache_op := _.
  Definition tlbi : Type := unit.
  Definition tlbi_eq : EqDecision tlbi := _.
  Definition tlbi_countable : Countable tlbi := _.
  Definition exn : Type := unit.
  Definition exn_eq : EqDecision exn := _.
  Definition exn_countable : Countable exn := _.
  Definition sys_reg_id : Type := unit.
  Definition sys_reg_id_eq : EqDecision sys_reg_id := _.
  Definition sys_reg_id_countable : Countable sys_reg_id := _.
End Arch.

Module Interface := SailStdpp.ConcurrencyInterfaceV2.Interface Arch.
Module Defs := SailStdpp.ConcurrencyInterfaceBuiltinsV2.Defs Arch Interface.

Definition M := Defs.monad unit.
Definition MR r := Defs.monad (r + unit)%type.
Definition returnM {A:Type} : A -> M A := Defs.returnm (E := unit).
Definition returnR {A:Type} (R:Type) : A -> MR R A := Defs.returnm (E := R + unit)%type.